version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
      - /workspace/frontend/node_modules
      - /workspace/backend/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development

  db:
    image: postgres:16.6
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data: